Controllers/MarketsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using StockPortfolio.Data;

namespace StockPortfolio.Controllers
{
    public class MarketsController : Controller
    {
        public async Task<IActionResult> Index()
        {
            var marketList = await YHFinanceAPIClient.ProcessMarkets();
            return View(marketList);
        }
    }
}

Controllers/PortfolioStocksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StockPortfolio.Data;
using StockPortfolio.Models;

namespace StockPortfolio.Controllers
{
    public class PortfolioStocksController : Controller
    {
        private readonly PortfolioContext _context;

        public PortfolioStocksController(PortfolioContext context)
        {
            _context = context;
        }

        // GET: PortfolioStocks
        public async Task<IActionResult> Index()
        {
            var portfolioStocks = await _context.PortfolioStocks.OrderBy(m => m.Symbol).ToListAsync();
            var symbolsStr = string.Join(",", portfolioStocks.Select(p => p.Symbol.ToString()));
            ViewBag.quoteList = await YHFinanceAPIClient.ProcessQuotes(symbolsStr);
            return View(portfolioStocks);
        }

        // GET: PortfolioStocks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var portfolioStock = await _context.PortfolioStocks
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.ID == id);
            if (portfolioStock == null)
            {
                return NotFound();
            }

            return View(portfolioStock);
        }

        // GET: PortfolioStocks/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PortfolioStocks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Symbol,CompanyName")] PortfolioStock portfolioStock)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(portfolioStock);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (DbUpdateException ex)
            {
                ModelState.AddModelError("", "Unable to save changes.");
            }
            return View(portfolioStock);
        }


        // GET: PortfolioStocks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var portfolioStock = await _context.PortfolioStocks.FindAsync(id);
            if (portfolioStock == null)
            {
                return NotFound();
            }
            return View(portfolioStock);
        }

        // POST: PortfolioStocks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPost(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var portfolioStockToUpdate = await _context.PortfolioStocks
                .FirstOrDefaultAsync(p => p.ID == id);
            if (await TryUpdateModelAsync<PortfolioStock>(portfolioStockToUpdate, "", p => p.Symbol, p => p.CompanyName, p => p.Currency))
            {
                try
                {
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateException ex)
                {
                    ModelState.AddModelError("", "Unable to save changes.");
                }
            }
            return View(portfolioStockToUpdate);
        }


        // GET: PortfolioStocks/Delete/5
        public async Task<IActionResult> Delete(int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return NotFound();
            }

            var portfolioStock = await _context.PortfolioStocks
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.ID == id);
            if (portfolioStock == null)
            {
                return NotFound();
            }
            if (saveChangesError.GetValueOrDefault())
            {
                ViewData["ErrorMessage"] = "Delete failed.";
            }

            return View(portfolioStock);
        }

        // POST: PortfolioStocks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var portfolioStock = await _context.PortfolioStocks.FindAsync(id);
            if (portfolioStock == null)
            {
                return RedirectToAction(nameof(Index));
            }
            try
            {
                _context.PortfolioStocks.Remove(portfolioStock);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException ex)
            {
                return RedirectToAction(nameof(Delete), new { id = id, saveChangesError = true });
            }
        }


        private bool PortfolioStockExists(int id)
        {
            return _context.PortfolioStocks.Any(e => e.ID == id);
        }
    }
}

Controllers/StocksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StockPortfolio.Data;
using StockPortfolio.Models;

namespace StockPortfolio.Controllers
{
    public class StocksController : Controller
    {
        private readonly PortfolioContext _context;

        public StocksController(PortfolioContext context)
        {
            _context = context;
        }

        // GET: Stocks
        public async Task<IActionResult> Index()
        {
            var stocks = await _context.Stocks.OrderBy(m => m.Symbol).ToListAsync();
            var symbolsStr = string.Join(",", stocks.Select(s => s.Symbol.ToString()));
            ViewBag.quoteList = await YHFinanceAPIClient.ProcessQuotes(symbolsStr);
            return View(stocks);
        }

        // GET: Stocks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var stock = await _context.Stocks
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.ID == id);

            if (stock == null)
            {
                return NotFound();
            }

            return View(stock);
        }

        // GET: Stocks/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Stocks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Symbol,CompanyName")] Stock stock)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    stock.Symbol = stock.Symbol.ToUpper();
                    _context.Add(stock);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (DbUpdateException ex)
            {
                ModelState.AddModelError("", "Unable to save changes.");
            }
            return View(stock);
        }

        // GET: Stocks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var stock = await _context.Stocks.FindAsync(id);
            if (stock == null)
            {
                return NotFound();
            }
            return View(stock);
        }

        // POST: Stocks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPost(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var stockToUpdate = await _context.Stocks
                .FirstOrDefaultAsync(s => s.ID == id);

            if (await TryUpdateModelAsync<Stock>(stockToUpdate, "", s => s.Symbol, s => s.CompanyName))
            {
                try
                {                   
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateException ex)
                {
                    ModelState.AddModelError("", "Unable to save changes.");
                }
            }

            return View(stockToUpdate);
        }

        // GET: Stocks/Delete/5
        public async Task<IActionResult> Delete(int? id, bool? saveChangesError = false)
        { 
            if (id == null)
            {
                return NotFound();
            }

            var stock = await _context.Stocks
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.ID == id);
            if (stock == null)
            {
                return NotFound();
            }

            if (saveChangesError.GetValueOrDefault())
            {
                ViewData["ErrorMessage"] = "Delete failed.";
            }

            return View(stock);
        }


        // POST: Stocks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var stock = await _context.Stocks.FindAsync(id);
            if (stock == null)
            {
                return RedirectToAction(nameof(Index));
            }

            try
            {
                _context.Stocks.Remove(stock);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException ex)
            {
                return RedirectToAction(nameof(Delete), new { id = id, saveChangesError = true });
            }
        }


        private bool StockExists(int id)
        {
            return _context.Stocks.Any(e => e.ID == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StockPortfolio</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">StockPortfolio</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Stocks" asp-action="Index">Watchlist</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PortfolioStocks" asp-action="Index">Portfolio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PortfolioStockTransactions" asp-action="Index">Portfolio Transactions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Markets" asp-action="Index">Markets</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - StockPortfolio - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

@section Scripts {
    <script src="~/lib/jquery/dist/jquery.js"></script>

} 